<script src="https://kit.fontawesome.com/3f5b3fe9f7.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="css/navigatie1.css">
<link rel="stylesheet" href="css/footer1.css">
<link rel="stylesheet" href="css/index1.css">
<link rel="stylesheet" href="css/overons.css">
<link rel="stylesheet" href="css/bestellen.css">
<link rel="stylesheet" href="css/contact.css">
<link rel="stylesheet" href="css/blog.css">
<link rel="stylesheet" href="css/login.css">